# Generated by Django 4.0 on 2021-12-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_attendance_attend_joined_alter_message_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attend_joined',
            new_name='user_joined',
        ),
    ]
