# Generated by Django 4.0 on 2021-12-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_lesson_name_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
