# Generated by Django 4.0 on 2021-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_attendance_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='qr_url',
            field=models.URLField(null=True),
        ),
    ]
