# Generated by Django 4.0 on 2021-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_attendance_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_now',
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='qr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
