# Generated by Django 4.0 on 2021-12-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_alter_attendance_date_now_alter_attendance_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
