# Generated by Django 4.0 on 2021-12-31 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0019_alter_attendance_user_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user_joined',
            field=models.ManyToManyField(blank=True, related_name='attendance_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
