# Generated by Django 4.0.1 on 2022-01-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_onlineusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineusers',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
