# Generated by Django 4.0.1 on 2022-01-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_alter_onlineusers_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lessons/lesson/{lesson}%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('avaliable', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
    ]
